import { dark } from '@clerk/themes'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <ClerkProvider
        appearance={{
            baseTheme:dark
        }
        }>
            <html lang="en">
                <head>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
                </head>
                <body>{children}</body>
            </html>
        </ClerkProvider>
    )
  }
  